project/app/urls.py
from django.urls import path, include

from app.views import Register, create_project, project, edit_project, invite, add_participant, add_update, add_event

app_name = 'app'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', Register.as_view(), name='register'),
    path('create_project/', create_project, name='create_project'),
    path('<int:project_id>', project, name = 'project'),
    path('edit/<int:project_id>', edit_project, name='edit_project'),
    path('add_participant/<int:project_id>', add_participant, name='add_participant'),
    path('add_update/<int:project_id>', add_update, name='add_update'),
    path('add_event/<int:project_id>',add_event,name='add_event'),
    path('invites/', invite, name='invite'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from app.views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name = 'home'),
    path('projects/',include('app.urls')),
    path('profile/',include('user_profile.urls')),
]

project/user_profile/urls.py
from django.urls import path, include

from user_profile.views import user_profile

app_name = 'user_profile'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('<name>',user_profile, name='user_profile'),
]

project/app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass

class Project(models.Model):
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    name = models.CharField('Название проекта',
                            max_length=100)
    info = models.TextField('О проекте',
                            max_length=5000)
    status = models.BooleanField(default=False)


class Participant(models.Model):
    participant = models.ForeignKey(
                                    User,
                                    on_delete=models.CASCADE,
                                    )
    invite_status = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
    )

class ProjectUpdate(models.Model):
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
    )
    update = models.TextField(max_length=1000)

class ProjectEvent(models.Model):
    project = models.ForeignKey(
        Project,
        on_delete=models.CASCADE,
    )
    info = models.TextField(max_length=1000)
    date = models.DateField()
    duration = models.DurationField()

project/user_profile/models.py
from django.db import models

# Create your models here.

project/app/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import TextInput
from django.utils.dateparse import parse_duration
from django.utils.translation import gettext_lazy as _

from .models import Project, Participant, ProjectUpdate, ProjectEvent

User = get_user_model()


class UserCreationForm(UserCreationForm):
    email = forms.EmailField(
        label=_('Email'),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )

    class Meta(UserCreationForm.Meta):
        model = User


class ProjectCreationForm(forms.ModelForm):
    class Meta():
        model = Project
        fields = ['name', 'info']


class ParticipantAddForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['participant'].empty_label = "Участник не выбран"

    class Meta():
        model = Participant
        fields = ['participant']


class ProjectEditForm(forms.ModelForm):
    class Meta():
        model = Project
        fields = ['name', 'info']


class ProjectUpdateAddForm(forms.ModelForm):
    class Meta():
        model = ProjectUpdate
        fields = ['update']


class ProjectEventAddForm(forms.ModelForm):
    class Meta():
        model = ProjectEvent
        fields = ['info', 'date', 'duration']
        widgets = {
            'date': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
            }),
            'info': forms.Textarea(attrs={
                'cols': 80,
                'rows': 2,
            }),
        }

project/app/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from app.forms import UserCreationForm, ProjectCreationForm, ParticipantAddForm, ProjectEditForm, ProjectUpdateAddForm, \
    ProjectEventAddForm
from app.models import Project, Participant, ProjectUpdate, ProjectEvent
from app.service import _create_project, _home_page, Project_page, _edit_project_post, _invite_page_info, \
    _add_participant_post, _add_update_post, _add_event_post


class Register(View):
    template_name = 'registration/register.html'

    def get(self, request):
        context = {
            'form': UserCreationForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('home')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


def create_project(request):
    if request.method == "POST":
        _create_project(request)
        return redirect('home')
    project = ProjectCreationForm()
    return render(request,
                  'create_project.html',
                  {'project': project}
                  )


def home_page(request):
    info = _home_page(request)
    return render(request,
                  'home.html',
                  info,
                  )


def project(request, project_id):
    if request.method == 'POST':
        dir = Project_page()._project_post(request, project_id)
        return redirect(dir)
    info = Project_page()._project_info(request, project_id)
    return render(request, 'project.html', info)


def edit_project(request, project_id):
    project = get_object_or_404(Project, id=project_id)
    if request.user.id == project.owner.id:
        if request.method == 'POST':
            _edit_project_post(request, project)
            return redirect('home')
        elif request.method == 'GET':
            return render(request,
                          'edit_project.html',
                          {'project': project,
                           })
    return redirect('home')


def invite(request):
    info = _invite_page_info(request)
    return render(request, 'invite.html', info)


def add_participant(request, project_id):
    if request.method == 'POST':
        _add_participant_post(request, project_id)
        return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))
    else:
        participant = ParticipantAddForm()
    return render(request,
                  'add_participant.html',
                  {'participant': participant,
                   })


def add_update(request, project_id):
    if request.method == 'POST':
        _add_update_post(request, project_id)
        return redirect(f'../{project_id}')
    else:
        update = ProjectUpdateAddForm()
    return render(request, 'add_update.html', {
        'update': update,
    })


def add_event(request, project_id):
    if request.method == 'POST':
        _add_event_post(request, project_id)
        return redirect(f'../{project_id}')
    else:
        event = ProjectEventAddForm()
    return render(request, 'add_event.html', {
        'event': event,
    })

project/user_profile/views.py
from django.shortcuts import render, redirect

from app.models import User, Project, Participant


def user_profile(request,name):
    user_info = User.objects.filter(username = name).get()
    user_projects = Project.objects.filter(owner = user_info.id).all()
    user_participant = Participant.objects.filter(participant = user_info.id).all()
    owner = request.user.id
    return render(request,
                  'user_profile.html',
                  {'user_info':user_info,
                   'owner':owner,
                   'user_projects':user_projects,
                   'user_participant':user_participant
                   })

project/app/templates/add_event.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{event.as_p}}
  <input type="submit" value="Добавить" class="btn btn-success"> <input type="button" onclick="history.back();" value="Назад" class="btn btn-success"/>
</form>
{% endblock %}

project/app/templates/add_participant.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    Участник: {{participant.participant}}
    <input type="submit" value="Добавить" class="btn btn-success"> <input type="button" onclick="history.back();" value="Назад" class="btn btn-success"/>
</form>
{% endblock %}

project/app/templates/add_update.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
  {% csrf_token %}
  {{update}}
  <input type="submit" value="Добавить" class="btn btn-success"> <input type="button" onclick="history.back();" value="Назад" class="btn btn-success"/>
</form>
{% endblock %}

project/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Title</title>
  <script>console.log(123)</script>
</head>
<body class="container">
<ul class="list-group">
  <li class="list-group-item">
    Пользователь: {{user}}
    {% if user.is_authenticated %}
        <a href="{% url 'app:logout' %}">Выйти</a>
  {% else %}
        <a href="{% url 'app:login' %}">Войти</a> |
        <a href="{% url 'app:register' %}">Зарегистрироваться</a>
  {% endif %}
  </li>
  <li class="list-group-item">
    <a href="{% url 'home' %}">На главную</a> {% if user.is_authenticated %}| <a href="/profile/{{user}}">Профиль</a> | <a href="{% url 'app:invite' %}">Приглашения</a> | <a href="{% url 'app:create_project' %}">Создать проект</a>{% endif %}
  </li>
</ul>

{% block content %}
{% endblock %}

</body>
</html>

project/app/templates/create_project.html
{% extends 'base.html' %}

{% block content %}
<form action=" {% url 'app:create_project' %}" method="post" id="create">
    {% csrf_token %}
    {{project.as_p}} <br>
    <input type="submit" value="Создать" form="create" class="btn btn-success">
</form>
{% endblock %}

project/app/templates/edit_project.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}

<div class="input-group">
  <span class="input-group-text">Название</span>
  <textarea class="form-control" aria-label="With textarea" name ='name'>{{project.name}}</textarea>
</div>
    <div class="input-group">
      <span class="input-group-text">О проекте</span>
      <textarea class="form-control" aria-label="With textarea" name="info">{{project.info}}</textarea>
    </div>

<input type="submit" value="Изменить" class="btn btn-success"> <input type="button" onclick="history.back();" value="Назад" class="btn btn-success"/>
</form>
{% endblock %}

project/app/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Главная страница</h1>
  <hr>

    {% if user.is_authenticated %}
    {% if projects %}
    <h2>Ваши проекты:</h2><br>
<table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Название</th>
              <th scope="col">Создатель</th>
            </tr>
          </thead>
            {% for i in projects %}
            <tbody>
                <tr>
                    <th scope="row">{{i.id}}</th>
                    <td><a href='projects/{{i.id}}'>{{i.name}}</a></td>
                    <td>{{i.owner}}</td>
                </tr>
            </tbody>
            {% endfor %}
</table>

    {% endif %}
    {% if participant %}
    <h2>Проекты в которых участвуете:</h2><br>
    <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Название</th>
              <th scope="col">Создатель</th>
            </tr>
          </thead>
        {% for i in participant %}
            {% if i.invite_status == True %}
                <tbody>
                    <tr>
                        <th scope="row">{{i.project.id}}</th>
                        <td><a href='projects/{{i.project.id}}'>{{i.project.name}}</a></td>
                        <td>{{i.project.owner}}</td>
                    </tr>
                </tbody>
            {% endif %}
        {% endfor %}
    {% endif %}
    </table>
    {% endif %}
<h2>Все проекты:</h2><br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Название</th>
      <th scope="col">Создатель</th>
    </tr>
  </thead>
{% for i in all_projects %}
{% if i.owner.id != user_id %}
    <tbody>
        <tr>
            <th scope="row">{{i.id}}</th>
            <td><a href='projects/{{i.id}}'>{{i.name}}</a></td>
            <td>{{i.owner}}</td>
        </tr>
    </tbody>

{% endif %}
{% endfor %}
</table>
{% endblock %}

project/app/templates/invite.html
{% extends 'base.html' %}

{% block content %}
<h1>Приглашения: </h1><br>

<form method="post" action="{% url 'app:invite' %}">
    {% csrf_token %}
    {% if participant %}
    <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Название</th>
              <th scope="col">Создатель</th>
            </tr>
          </thead>
    {% for i in participant %}
        {% if i.invite_status == False %}
            <tbody>
                <tr>
                    <th scope="row">{{i.project.id}}</th>
                    <td><a href='../{{i.project.id}}'>{{i.project.name}}</a></td>
                    <td>{{i.project.owner}}</td>
                </tr>
            </tbody>
        {% endif %}
    {% endfor %}
    </table>
    {% else %}
        <h3>Нет приглашений</h3>
    {% endif %}
</form>

{% endblock %}

project/app/templates/project.html
{% extends 'base.html' %}

{% block content %}
<h1>Проект {{project.name}}</h1>

<h2>О проекте:</h2> <p class="lh-sm">{{project.info}}</p>
{% if update %}
    {% for i in update %}
        {{i.update}}
    {% endfor %}
{% endif %}
{% if event %}
    {{event}}
{% endif %}
<h3>Создатель проекта: {{project.owner}}</h3>
{% if participant %}
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Пользователь</th>
    </tr>
  </thead>
        <h4>Участники:</h4>
        {% for i in participant %}
                {% if i.invite_status == True %}
                        <tbody>
                            <tr>
                              <th scope="row">{{i.participant.id}}</th>
                              <td><a href="../profile/{{i.participant.username}}">{{i.participant.username}}</a></td>
                            </tr>
                        </tbody>
                {% endif %}
        {% endfor %}
</table>
{% endif %}
{% for i in participant %}
    {% if i.participant.id == user_id and i.invite_status == True %}
        <form method="post">
            {% csrf_token %}
            <th scope="row"><input type="submit" value="Покинуть проект" name="leave" class="btn btn-secondary"></th>
        </form>
    {% endif %}
{% endfor %}
<form method="post">
        {% csrf_token %}
            {% if user_id == participant_invite.participant.id and participant_invite.invite_status == False %}
                <h4>Приглашение для вступления в проект
                        <input type="submit" value="Присоедениться" name="join" class="btn btn-success">
                        <input type="submit" value="Отклонить" name="decline" class="btn btn-secondary"> <br>
                </h4>
            {% endif %}
</form>
{% if project.owner.id == user_id %}
        <a href='edit/{{project.id}}'>Изменить информацию</a> |
        <a href="add_participant/{{project.id}}">Добавить участников</a> |
        <a href="add_update/{{project.id}}">Добавить информацию об обновлении проекта</a> |
        <a href="add_event/{{project.id}}">Добавить мероприяетие</a><br>
        <form method="post">
                {% csrf_token %}
                <input type="submit" name="delete_project" value="Удалить проект" class="btn btn-secondary">
        </form>
{% endif %}
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Title</title>
  <script>console.log(123)</script>
</head>
<body class="container">
<ul class="list-group">
  <li class="list-group-item">
    Пользователь: {{user}}
  </li>
  <li class="list-group-item">
    <a href="{% url 'home' %}">На главную</a>
  </li>
</ul>

{% block content %}
{% endblock %}

</body>
</html>

project/templates/create_project.html
{% extends 'base.html' %}

{% block content %}
<form action=" {% url 'app:create_project' %}" method="post" id="create">
    {% csrf_token %}
    {{project.as_p}} <br>
<!--    {{participant}} <button type="button" value="add" formaction="add_participant">Добавить еще участника</button>-->
    <input type="submit" value="Создать" form="create">
</form>
{% endblock %}

project/templates/edit_project.html
{% extends 'base.html' %}

{% block content %}
<form method="post">
    {% csrf_token %}

<div class="input-group">
  <span class="input-group-text">Название</span>
  <textarea class="form-control" aria-label="With textarea" name ='name'>{{project.name}}</textarea>
</div>
    <div class="input-group">
      <span class="input-group-text">О проекте</span>
      <textarea class="form-control" aria-label="With textarea" name="info">{{project.info}}</textarea>
    </div>

<input type="submit" value="Изменить" class="btn btn-success">
</form>
{% endblock %}

project/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h1>Главная страница</h1>
  <hr>

  {% if user.is_authenticated %}
        <a href="{% url 'app:logout' %}">Выйти</a> |
        <a href="{% url 'app:create_project' %}">Создать проект</a> |
        <a href="{% url 'app:invite' %}">Приглашения</a>
  {% else %}
        <a href="{% url 'app:login' %}">Войти</a> |
        <a href="{% url 'app:register' %}">Зарегистрироваться</a>
  {% endif %}
    {% if user.is_authenticated %}
    {% if projects %}
    <h2>Ваши проекты:</h2><br>
<table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Название</th>
              <th scope="col">Создатель</th>
            </tr>
          </thead>
            {% for i in projects %}
            <tbody>
                <tr>
                    <th scope="row">{{i.id}}</th>
                    <td><a href='projects/{{i.id}}'>{{i.name}}</a></td>
                    <td>{{i.owner}}</td>
                </tr>
            </tbody>
            {% endfor %}
</table>

    {% endif %}
    {% if participant %}
    <h2>Проекты в которых участвуете:</h2><br>
    <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Название</th>
              <th scope="col">Создатель</th>
            </tr>
          </thead>
        {% for i in participant %}
        {% if i.invite_status == True %}
        <tbody>
            <tr>
                <th scope="row">{{i.project.id}}</th>
                <td><a href='projects/{{i.project.id}}'>{{i.project.name}}</a></td>
                <td>{{i.project.owner}}</td>
            </tr>
        </tbody>
        {% endif %}
        {% endfor %}
    {% endif %}
    </table>
    {% endif %}
<h2>Все проекты:</h2><br>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Название</th>
      <th scope="col">Создатель</th>
    </tr>
  </thead>
{% for i in all_projects %}
{% if i.owner.id != user_id %}
    <tbody>
        <tr>
            <th scope="row">{{i.id}}</th>
            <td><a href='projects/{{i.id}}'>{{i.name}}</a></td>
            <td>{{i.owner}}</td>
        </tr>
    </tbody>

{% endif %}
{% endfor %}
</table>
{% endblock %}

project/templates/project.html
{% extends 'base.html' %}

{% block content %}
<h1>Проект {{project.name}}</h1>

<h2>О проекте:</h2> <p class="lh-sm">{{project.info}}</p>

<h3>Создатель проекта: {{project.owner}}</h3>
{% if participant %}
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Пользователь</th>
    </tr>
  </thead>
        <h4>Участники:</h4>
        {% for i in participant %}
                {% if i.invite_status == True %}
                        <tbody>
                            <tr>
                              <th scope="row">{{i.participant.id}}</th>
                              <td>{{i.participant.username}}</td>
                            </tr>
                        </tbody>
                {% endif %}
        {% endfor %}
</table>
{% endif %}
<form method="post">
        {% csrf_token %}
        {% if user_id == participant_invite.participant.id and participant_invite.invite_status == False %}
        <h4>Приглашение для вступления в проект
                <input type="submit" value="Присоедениться" name="join" class="btn btn-success">
                <input type="submit" value="Отклонить" name="decline" class="btn btn-secondary"> <br>
        </h4>
        {% endif %}
</form>
{% if project.owner.id == user_id %}
        <a href='edit/{{project.id}}'>Изменить информацию</a>
        <a href="add_participant/{{project.id}}">Добавить участников</a> <br>
        <form method="post">
                {% csrf_token %}
                <input type="submit" name="delete_project" value="Удалить проект" class="btn btn-secondary">
        </form>
{% endif %}
{% endblock %}

project/user_profile/templates/user_profile.html
{% extends 'base.html' %}

{% block content %}
    {% if user_projects %}
    <h2>Проекты {{user_info.username}}:</h2><br>
<table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Название</th>
              <th scope="col">Создатель</th>
            </tr>
          </thead>
            {% for i in user_projects %}
            <tbody>
                <tr>
                    <th scope="row">{{i.id}}</th>
                    <td><a href='../projects/{{i.id}}'>{{i.name}}</a></td>
                    <td>{{i.owner}}</td>
                </tr>
            </tbody>
            {% endfor %}
</table>

    {% endif %}
    {% if user_participant %}
    <h2>Проекты в которых участвует:</h2><br>
    <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">ID</th>
              <th scope="col">Название</th>
              <th scope="col">Создатель</th>
            </tr>
          </thead>
        {% for i in user_participant %}
            {% if i.invite_status == True %}
                <tbody>
                    <tr>
                        <th scope="row">{{i.project.id}}</th>
                        <td><a href='../projects/{{i.project.id}}'>{{i.project.name}}</a></td>
                        <td>{{i.project.owner}}</td>
                    </tr>
                </tbody>
            {% endif %}
        {% endfor %}
    {% endif %}
    </table>
{% if owner == user_info.id %}
Твоя страничка
{% endif %}
{% endblock %}